apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: churn
spec:
  name: churn
  predictors:
  - componentSpecs:
    - spec:
      containers:
      - name: classifier
        image: seldonio/sklearnserver_rest:1.2.3
    graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: gs://mavencode-churn-model/customer-churn/churn01
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: default
    replicas: 1